[package]
name = "inverted-index"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-stemmers = "1.2.0"
stop-words = "0.8.0"
unicode-segmentation = "1.10.1"
