[package]
name = "mongo-crud"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
mongodb = "2.8.1"
serde = "1.0.196"
tokio = "1.36.0"
